### ISSUE TITLE
Event Registration / RSVP

### ISSUE THREAD

**Issue by kevinschoonover** [MST-ACM/ACM_Website#168]
## Problem Description
Events such as Wireless Workshop need a list of the number of people who will be attending so that they can organize supplies and food. Moreover, "Premium Events" require an accurate list of who payed to attend the event for a proper audit of participation. To solve these two problems, we need to implement the ability to register or RSVP for specific events.

## To-Do List

- [ ] Implement the ability for a User to register for a specific event and be permanently associated with the Event for later querying
- [ ] Have a registration "deadline" which only allows users to register up to the deadline. Defaults to the  time of the start of the event
- [ ] Create a page so that event creators can see who has RSVPed / Registered for a given event
- [ ] Limit the resigstration up to "max_capacity"
