### ISSUE TITLE
Automatic Event Notification

### ISSUE THREAD

**Issue by kevinschoonover** [MST-ACM/ACM_Website#169]
## Problem Description
Everytime ACM General creates an event, they need to send an email to cstask to request for printing and forwarding to the entire CS department's email list. Moreover, the creator of the event needs to properly notify their own email group the day of. With the website, when the event creator submits an event to the website, we can automatically notify these groups or create weekly digests with the information collected.

## To-Do list

- [ ] Submit a job to a weekly task runner such as celery beat to create a weekly digest for every event created that week.
- [ ] Send this weekly digest to acm@mst.edu or cstask@mst.edu in order to properly advertise / create fliers for the event.
- [ ] Allow users to specify notification times, email lists for these notifications, and notification messages
